namespace LifeAlertPlus.Client.Services
{
    public class LanguageService
    {
        public string CurrentLanguage { get; private set; } = "en";

        public event Action? OnLanguageChanged;

        public void SetLanguage(string lang)
        {
            if (lang != CurrentLanguage)
            {
                CurrentLanguage = lang;
                OnLanguageChanged?.Invoke();
            }
        }

        public string T(string key)
        {
            if (CurrentLanguage == "ro" && _ro.TryGetValue(key, out var ro))
                return ro;
            if (CurrentLanguage == "en" && _en.TryGetValue(key, out var en))
                return en;
            // fallback: return key itself
            return key;
        }

        public string TEnglish(string key)
        {
            return _en.TryGetValue(key, out var en) ? en : key;
        }

        // ── English ──
        private static readonly Dictionary<string, string> _en = new()
        {
            // Header / Nav
            ["nav.dashboard"] = "Dashboard",
            ["nav.monitored"] = "Monitored",
            ["nav.notifications"] = "Notifications",
            ["nav.profile"] = "My Profile",
            ["nav.settings"] = "Settings",
            ["nav.aboutUs"] = "About Us",
            ["nav.support"] = "Support",
            ["nav.logout"] = "Logout",
            ["nav.menu"] = "Menu",

            // Login
            ["login.title"] = "LifeAlert +",
            ["login.tagline"] = "Because every heartbeat matters",
            ["login.email"] = "Email",
            ["login.password"] = "Password",
            ["login.button"] = "Login",
            ["login.loading"] = "Login...",
            ["login.or"] = "or",
            ["login.google"] = "Login with Google",
            ["login.forgotPassword"] = "Forgot your password?",
            ["login.createAccount"] = "Create a new account",
            ["login.resetPassword"] = "Reset Password",
            ["login.resetText"] = "Enter your email address and we'll send you a link to reset your password.",
            ["login.sendResetLink"] = "Send Reset Link",
            ["login.cancel"] = "Cancel",
            ["login.close"] = "Close",

            // Login errors
            ["login.error.failed"] = "Login failed.",
            ["login.error.generic"] = "An error occurred during login.",
            ["login.error.enterEmail"] = "Please enter your email address.",
            ["login.error.validEmail"] = "Please enter a valid email address.",
            ["login.error.resetFailed"] = "Failed to send reset email. Please try again.",
            ["login.error.resetGeneric"] = "An error occurred. Please try again later.",

            // Register
            ["register.title"] = "Register",
            ["register.loading"] = "Register...",
            ["register.firstName"] = "First Name",
            ["register.lastName"] = "Last Name",
            ["register.email"] = "Email",
            ["register.password"] = "Password",
            ["register.confirmPassword"] = "Confirm Password",
            ["register.hasAccount"] = "Already have an account? Login",
            ["register.success"] = "Registration Successful",
            ["register.emailSent"] = "An email has been sent for verification.",
            ["register.ok"] = "OK",

            // Register errors
            ["register.error.allRequired"] = "All fields are required.",
            ["register.error.passwordMismatch"] = "Passwords do not match.",
            ["register.error.failed"] = "Registration failed. Please try again.",

            // Password validation
            ["password.required"] = "Password is required.",
            ["password.minLength"] = "Password must be at least 8 characters long.",
            ["password.lowercase"] = "Password must contain at least one lowercase letter.",
            ["password.uppercase"] = "Password must contain at least one uppercase letter.",
            ["password.number"] = "Password must contain at least one number.",
            ["password.special"] = "Password must contain at least one special character.",

            // Dashboard
            ["dashboard.title"] = "Dashboard",
            ["dashboard.welcome"] = "Welcome back, {0}! Here's your health monitoring overview.",
            ["dashboard.totalMonitored"] = "Total Monitored",
            ["dashboard.activeAlerts"] = "Active Alerts",
            ["dashboard.stableStatus"] = "Stable Status",
            ["dashboard.usersOffline"] = "Users Offline",
            ["dashboard.measurementsToday"] = "Total Measurements Today",
            ["dashboard.monitoredPeople"] = "Monitored People",
            ["dashboard.viewAll"] = "View All →",

            // Shared card labels
            ["card.pulse"] = "Pulse (bpm)",
            ["card.spo2"] = "SpO₂ (%)",
            ["card.temperature"] = "Temperature (°C)",
            ["card.gps"] = "📍 GPS:",
            ["card.fallDetection"] = "🧭 Fall detection:",
            ["card.lastUpdate"] = "⏰ Last Update:",
            ["card.location"] = "Location",
            ["card.call"] = "Call",
            ["card.text"] = "Text",
            ["card.na"] = "N/A",

            // Status
            ["status.ok"] = "OK",
            ["status.warning"] = "Warning",
            ["status.critical"] = "Critical",
            ["status.offline"] = "Offline",
            ["status.online"] = "Online",

            // Monitored page
            ["monitored.title"] = "Monitored People",
            ["monitored.subtitle"] = "Manage and view all people you're monitoring",
            ["monitored.addPerson"] = "Add New Person",
            ["monitored.statusFilter"] = "Status Filter:",
            ["monitored.connectionFilter"] = "Connection Filter:",
            ["monitored.all"] = "All",
            ["monitored.alert"] = "Alert",
            ["monitored.checkNeeded"] = "Check Needed",
            ["monitored.stable"] = "Stable",
            ["monitored.online"] = "Online",
            ["monitored.offline"] = "Offline",
            ["monitored.loading"] = "Loading monitored people...",
            ["monitored.noMonitored"] = "No monitored people",
            ["monitored.addToStart"] = "Add a person to start receiving ESP data.",
            ["monitored.noResults"] = "No results found",
            ["monitored.noMatch"] = "No monitored people match the selected filters.",
            ["monitored.ageYears"] = "years",
            ["monitored.ageNA"] = "Age N/A",

            // Add person modal
            ["modal.addPerson"] = "Add Monitored Person",
            ["modal.firstName"] = "First Name",
            ["modal.lastName"] = "Last Name",
            ["modal.birthdate"] = "Birthdate",
            ["modal.gender"] = "Gender",
            ["modal.select"] = "Select...",
            ["modal.male"] = "Male",
            ["modal.female"] = "Female",
            ["modal.other"] = "Other",
            ["modal.address"] = "Address",
            ["modal.deviceSerial"] = "Device Serial Number",
            ["modal.relationship"] = "Relationship",
            ["modal.cancel"] = "Cancel",
            ["modal.addButton"] = "Add Person",

            // Settings
            ["settings.title"] = "⚙️ Settings",
            ["settings.subtitle"] = "Personalize your application according to your preferences",
            ["settings.appearance"] = "🎨 Appearance",
            ["settings.firstDay"] = "First Day of the Week",
            ["settings.fontSize"] = "Font Size",
            ["settings.fontSizeDesc"] = "Adjust the text size in the application",
            ["settings.small"] = "Small",
            ["settings.medium"] = "Medium",
            ["settings.large"] = "Large",
            ["settings.monday"] = "Monday",
            ["settings.tuesday"] = "Tuesday",
            ["settings.wednesday"] = "Wednesday",
            ["settings.thursday"] = "Thursday",
            ["settings.friday"] = "Friday",
            ["settings.saturday"] = "Saturday",
            ["settings.sunday"] = "Sunday",
            ["settings.alertThresholds"] = "🚨 Alert Thresholds",
            ["settings.heartRate"] = "❤️ Heart Rate",
            ["settings.heartRateMin"] = "Heart Rate Min",
            ["settings.heartRateMax"] = "Heart Rate Max",
            ["settings.temperatureSection"] = "🌡️ Temperature",
            ["settings.tempMin"] = "Temperature Min",
            ["settings.tempMax"] = "Temperature Max",
            ["settings.resetDefaults"] = "🔄 Reset to default values",
            ["settings.dataManagement"] = "💾 Data Management",
            ["settings.updateFrequency"] = "Data Update Frequency",
            ["settings.updateFrequencyDesc"] = "How often vital signs data is refreshed (in seconds)",
            ["settings.every10s"] = "Every 10 seconds",
            ["settings.every15s"] = "Every 15 seconds",
            ["settings.every30s"] = "Every 30 seconds",
            ["settings.every1m"] = "Every 1 minute",
            ["settings.every2m"] = "Every 2 minutes",
            ["settings.every5m"] = "Every 5 minutes",
            ["settings.historyRetention"] = "History Retention Duration",
            ["settings.historyRetentionDesc"] = "How long to keep old data",
            ["settings.30days"] = "30 days",
            ["settings.90days"] = "90 days",
            ["settings.6months"] = "6 months",
            ["settings.1year"] = "1 year",
            ["settings.unlimited"] = "Unlimited",
            ["settings.system"] = "🔧 System",
            ["settings.language"] = "Language",
            ["settings.languageDesc"] = "Select the application language",
            ["settings.systemInfo"] = "📊 System Information",
            ["settings.appVersion"] = "Application Version:",
            ["settings.lastUpdate"] = "Last Update:",
            ["settings.usedSpace"] = "Used Space:",
            ["settings.saveAll"] = "💾 Save All Settings",
            ["settings.resetAll"] = "🔄 Reset All",
            ["settings.saved"] = "✅ Settings have been saved successfully!",

            // Notifications
            ["notifications.title"] = "Notifications",
            ["notifications.subtitle"] = "Stay updated with all health alerts and updates",
            ["notifications.criticalAlerts"] = "Critical Alerts",
            ["notifications.warnings"] = "Warnings",
            ["notifications.infoMessages"] = "Info Messages",
            ["notifications.unread"] = "Unread",

            // Support
            ["support.tagline"] = "We're here to help",
            ["support.title"] = "Support",
            ["support.backToDashboard"] = "← Back to Dashboard",

            // Profile
            ["profile.memberSince"] = "Member since {0}",
            ["profile.personalInfo"] = "📋 Personal information",
            ["profile.edit"] = "✏️ Edit",
            ["profile.save"] = "💾 Save",
            ["profile.cancel"] = "✖️ Cancel",
            ["profile.firstName"] = "First Name",
            ["profile.lastName"] = "Last Name",
            ["profile.security"] = "🔒 Security",
            ["profile.changePassword"] = "Change Password",

            // Common
            ["common.save"] = "Save",
            ["common.cancel"] = "Cancel",
            ["common.close"] = "Close",
            ["common.loading"] = "Loading...",
            ["common.retry"] = "Retry",
            ["common.details"] = "Details",
            ["common.bpm"] = "bpm",
            ["common.celsius"] = "°C",

            // About Us
            ["about.title"] = "About LifeAlertPlus",
            ["about.intro"] = "LifeAlertPlus is an IoT-based monitoring system designed to improve the safety and quality of life of elderly individuals. By combining wearable technology with a modern web platform, the system enables real-time monitoring of activity and health-related data.",
            ["about.missionTitle"] = "Our Mission",
            ["about.missionText"] = "Our mission is to support independent living while ensuring safety through continuous monitoring and timely alerts. LifeAlertPlus helps caregivers and family members stay informed and respond quickly in case of unusual events.",
            ["about.problemTitle"] = "The Problem",
            ["about.problemText"] = "Many elderly individuals live alone or spend long periods without direct supervision. Incidents like falls, inactivity, or sudden health issues may go unnoticed, leading to delayed assistance and increased risks.",
            ["about.visionTitle"] = "Our Vision",
            ["about.visionText"] = "We aim to create a reliable and accessible monitoring system that enhances safety, promotes independence, and provides peace of mind for both users and their families.",
            ["about.solutionTitle"] = "Our Solution",
            ["about.solutionIntro"] = "LifeAlertPlus provides a complete solution that integrates:",
            ["about.solutionWearable"] = "Wearable IoT device for collecting activity data",
            ["about.solutionWeb"] = "Web-based application for real-time monitoring",
            ["about.solutionAlerts"] = "Alert mechanisms for detecting abnormal situations",
            ["about.featuresTitle"] = "Key Features",
            ["about.feature1"] = "Real-time activity monitoring",
            ["about.feature2"] = "Secure authentication and user management",
            ["about.feature3"] = "Email notifications and alerts",
            ["about.feature4"] = "Dashboard for caregivers and administrators",
            ["about.feature5"] = "Expandable architecture for future improvements",
            ["about.disclaimerTitle"] = "Disclaimer",
            ["about.disclaimerText"] = "LifeAlertPlus is not a medical device and does not replace professional medical services or emergency systems. In case of emergency, please contact local emergency services immediately.",

            // Support (extended)
            ["support.intro"] = "We are here to help you ensure that your LifeAlertPlus system works reliably and efficiently.",
            ["support.contactTitle"] = "Contact Us",
            ["support.contactText"] = "If you experience any issues with the application or the IoT device, please contact our support team:",
            ["support.contactNote"] = "We aim to respond to all inquiries as soon as possible.",
            ["support.beforeTitle"] = "Before Contacting Support",
            ["support.beforeText"] = "To resolve common issues quickly, please check the following:",
            ["support.checkCharged"] = "Make sure the device is properly charged",
            ["support.checkRestart"] = "Restart the device",
            ["support.checkInternet"] = "Verify that the device has an active internet connection",
            ["support.checkUpdate"] = "Ensure the application is up to date",
            ["support.commonTitle"] = "Common Issues",
            ["support.issueNoData"] = "Device not sending data",
            ["support.issueBattery"] = "Check battery level",
            ["support.issueRestart"] = "Restart the device",
            ["support.issueNotLoading"] = "Application not loading data",
            ["support.issueRefresh"] = "Refresh the page",
            ["support.issueConnection"] = "Check internet connection",
            ["support.issueLogin"] = "Login or authentication issues",
            ["support.issueResetPw"] = "Reset your password",
            ["support.issueVerifyEmail"] = "Ensure your email is verified",
            ["support.techTitle"] = "Technical Support",
            ["support.techText"] = "For technical inquiries or system-related issues, please include:",
            ["support.techDesc"] = "A description of the problem",
            ["support.techSteps"] = "Steps to reproduce the issue",
            ["support.techScreenshots"] = "Screenshots (if available)",
            ["support.autoTitle"] = "Automated Emails",
            ["support.autoText"] = "System-generated messages (account verification, password reset, notifications) are sent from:",
            ["support.autoNote"] = "This address is not monitored for incoming messages.",
            ["support.noticeTitle"] = "Service Notice",
            ["support.noticeText"] = "LifeAlertPlus is designed to assist monitoring and alerting but does not guarantee prevention of incidents. Always rely on emergency services in critical situations.",

            // Profile (extended)
            ["profile.changePicture"] = "Change Picture",
            ["profile.monitored"] = "Monitored",
            ["profile.activeAlerts"] = "Active Alerts",
            ["profile.lastChanged"] = "Last changed:",
            ["profile.never"] = "Never",
            ["profile.changePasswordBtn"] = "Change Password",
            ["profile.changeEmailTitle"] = "Change Email",
            ["profile.updateEmailDesc"] = "Update your email address",
            ["profile.changeEmailBtn"] = "Change Email",
            ["profile.passwordManaged"] = "Password Managed Externally",
            ["profile.passwordManagedText"] = "Your password is managed through",
            ["profile.emailManaged"] = "Email Managed Externally",
            ["profile.emailManagedText"] = "Your email is managed through",
            ["profile.notifPrefs"] = "Notification Preferences",
            ["profile.emailNotif"] = "Email Notifications",
            ["profile.emailNotifDesc"] = "Receive important alerts via email",
            ["profile.pushNotif"] = "Push Notifications",
            ["profile.pushNotifDesc"] = "Real-time alerts in your browser",
            ["profile.criticalAlerts"] = "Critical Alerts",
            ["profile.criticalAlertsDesc"] = "Priority notifications for emergency situations",
            ["profile.dailySummary"] = "Daily Summary",
            ["profile.dailySummaryDesc"] = "Receive a daily activity report",
            ["profile.dangerZone"] = "Danger Zone",
            ["profile.deleteAccount"] = "Delete Account",
            ["profile.deleteAccountDesc"] = "Permanent action, all data will be deleted",
            ["profile.deletePermanently"] = "Delete Permanently",
            ["profile.currentPassword"] = "Current Password",
            ["profile.currentPasswordPh"] = "Enter current password",
            ["profile.newPassword"] = "New Password",
            ["profile.newPasswordPh"] = "At least 8 characters",
            ["profile.confirmNewPassword"] = "Confirm New Password",
            ["profile.confirmNewPasswordPh"] = "Re-enter new password",
            ["profile.newEmail"] = "New Email",
            ["profile.newEmailPh"] = "Enter new email address",
            ["profile.confirmNewEmail"] = "Confirm New Email",
            ["profile.confirmNewEmailPh"] = "Re-enter new email address",
            ["profile.passwordToConfirmPh"] = "Enter your password to confirm",
            ["profile.emailChangedSuccess"] = "Email Changed Successfully",
            ["profile.emailChangedText1"] = "Your email address change request has been submitted successfully!",
            ["profile.emailChangedText2"] = "A confirmation email has been sent to your new email address. Please check your inbox and click the verification link to complete the process.",
            ["profile.emailChangedText3"] = "For security, we've also sent a notification to your current email address. If this wasn't you, you can cancel this request from that email.",
            ["profile.emailChangedNote"] = "For security reasons, you will be logged out automatically. Please log in again with your new email address after verification.",
            ["profile.okLogout"] = "OK, Log me out",
            ["profile.passwordChangedSuccess"] = "Password Changed Successfully",
            ["profile.passwordChangedText1"] = "Your password has been changed successfully!",
            ["profile.passwordChangedText2"] = "Please use your new password the next time you log in.",
            ["profile.ok"] = "OK",
            ["profile.areYouSure"] = "Are you sure?",
            ["profile.deleteConfirm1"] = "Are you sure you want to delete your account permanently?",
            ["profile.deleteConfirm2"] = "This action cannot be undone.",
            ["profile.deleteConfirm3"] = "Please make sure to back up any important data before proceeding.",
            ["profile.deleteConfirm4"] = "All your data will be permanently removed from our system.",
            ["profile.yes"] = "Yes",
            ["profile.accountDeleted"] = "Account Deleted",
            ["profile.accountDeletedText"] = "Your account has been deleted permanently. Thank you for using our service.",

            // Reset Password
            ["reset.password"] = "Password",
            ["reset.confirmPassword"] = "Confirm Password",
            ["reset.button"] = "Reset Password",
            ["reset.backToLogin"] = "Back to Login",

            // Reset password errors
            ["reset.error.invalidLink"] = "Invalid reset link. Please request a new password reset.",
            ["reset.error.passwordMismatch"] = "Passwords do not match.",
            ["reset.error.success"] = "Password reset successful! Redirecting to login...",
            ["reset.error.expired"] = "Reset link has expired. Please request a new password reset.",
            ["reset.error.failed"] = "Failed to reset password. Please try again.",
            ["reset.error.generic"] = "An error occurred. Please try again later.",

            // Selected Monitored
            ["selected.goBack"] = "Go Back to Monitored List",
            ["selected.export"] = "Export",
            ["selected.years"] = "years",
            ["selected.noAgeGender"] = "No age/gender info",
            ["selected.lastUpdate"] = "Last Update:",
            ["selected.device"] = "Device:",
            ["selected.editProfile"] = "Edit Profile",
            ["selected.heartRate"] = "Heart Rate",
            ["selected.noRecentMeasurements"] = "No recent measurements.",
            ["selected.noData"] = "No data available",
            ["selected.bloodOxygen"] = "Blood Oxygen (SpO₂)",
            ["selected.temperature"] = "Temperature",
            ["selected.gpsLocation"] = "GPS Location",
            ["selected.vitalSigns"] = "Vital Signs Evolution",
            ["selected.daily"] = "Daily",
            ["selected.weekly"] = "Weekly",
            ["selected.recentAlerts"] = "Recent Alerts",
            ["selected.recentMeasurements"] = "Recent Measurements",
            ["selected.loading"] = "Loading...",
            ["selected.notFound"] = "Monitored person not found.",
            ["selected.firstName"] = "First Name",
            ["selected.lastName"] = "Last Name",
            ["selected.gender"] = "Gender",
            ["selected.select"] = "Select...",
            ["selected.male"] = "Male",
            ["selected.female"] = "Female",
            ["selected.other"] = "Other",
            ["selected.birthdate"] = "Birthdate",
            ["selected.address"] = "Address",
            ["selected.deviceSerial"] = "Device Serial Number",
            ["selected.customRanges"] = "Custom Vital Ranges (leave blank to use your account defaults)",
            ["selected.minHr"] = "Min Heart Rate (bpm)",
            ["selected.maxHr"] = "Max Heart Rate (bpm)",
            ["selected.minTemp"] = "Min Temperature (°C)",
            ["selected.maxTemp"] = "Max Temperature (°C)",
            ["selected.updateFrequency"] = "Update Frequency (leave blank to use account default: {0} s)",
            ["selected.useDefault"] = "Use account default ({0} s)",
            ["selected.saving"] = "Saving...",

            // Relationships
            ["rel.select"] = "Select...",
            ["rel.mother"] = "Mother",
            ["rel.father"] = "Father",
            ["rel.grandmother"] = "Grandmother",
            ["rel.grandfather"] = "Grandfather",
            ["rel.aunt"] = "Aunt",
            ["rel.uncle"] = "Uncle",
            ["rel.husband"] = "Husband",
            ["rel.wife"] = "Wife",
            ["rel.sister"] = "Sister",
            ["rel.brother"] = "Brother",
            ["rel.friend"] = "Friend",
            ["rel.daughter"] = "Daughter",
            ["rel.son"] = "Son",
            ["rel.nephew"] = "Nephew",
            ["rel.niece"] = "Niece",

            // App
            ["app.notFound"] = "Not found",
            ["app.notFoundText"] = "Sorry, there's nothing at this address.",

            // Admin
            ["admin.title"] = "Admin Center",
            ["admin.subtitle"] = "Show all users and monitored persons",
            ["admin.liveData"] = "Live data",
            ["admin.loadingData"] = "Loading data...",
            ["admin.noData"] = "No users or monitored persons found.",
            ["admin.totalUsers"] = "Total users",
            ["admin.monitoredPersons"] = "Monitored persons",
            ["admin.online"] = "Online",
            ["admin.offline"] = "Offline",
            ["admin.alerts"] = "Alerts",
            ["admin.todayMeasurements"] = "Today Measurements",
            ["admin.notifications"] = "Notifications",
            ["admin.noNotifications"] = "No notifications",

            // Admin Nav
            ["adminNav.dashboard"] = "Dashboard",
            ["adminNav.monitoreds"] = "Monitoreds",
            ["adminNav.users"] = "Users",
            ["adminNav.simulations"] = "Simulations",
            ["adminNav.logout"] = "Logout",
            ["adminNav.menu"] = "Menu",
            ["adminNav.profile"] = "My Profile",
            ["adminNav.settings"] = "Settings",

            // Users page
            ["users.title"] = "Users Center",
            ["users.subtitle"] = "Accounts overview and status",
            ["users.liveOverview"] = "Live overview",
            ["users.totalUsers"] = "Total users",
            ["users.activeUsers"] = "Active users",
            ["users.inactiveUsers"] = "Inactive users",
            ["users.emailConfirmed"] = "Email confirmed",
            ["users.loading"] = "Loading users...",
            ["users.retry"] = "Retry",
            ["users.usersTitle"] = "Users",
            ["users.searchPh"] = "Search users...",
            ["users.all"] = "All",
            ["users.active"] = "Active",
            ["users.inactive"] = "Inactive",
            ["users.noUsersFound"] = "No users found for the current filter.",
            ["users.thUser"] = "User",
            ["users.thEmail"] = "Email",
            ["users.thMonitored"] = "Monitored",
            ["users.thProvider"] = "Provider",
            ["users.thStatus"] = "Status",
            ["users.thEmailConfirmed"] = "Email Confirmed",
            ["users.thActions"] = "Actions",
            ["users.details"] = "Details",
            ["users.deactivate"] = "Deactivate",
            ["users.activate"] = "Activate",
            ["users.delete"] = "Delete",

            // Monitored Users page
            ["monUsers.title"] = "Monitored Center",
            ["monUsers.subtitle"] = "Monitored persons and their monitors",
            ["monUsers.liveOverview"] = "Live overview",
            ["monUsers.monitored"] = "Monitored",
            ["monUsers.online"] = "Online",
            ["monUsers.offline"] = "Offline",
            ["monUsers.alerts"] = "Alerts",
            ["monUsers.loading"] = "Loading monitored users...",
            ["monUsers.retry"] = "Retry",
            ["monUsers.noPersons"] = "No monitored persons found.",
            ["monUsers.personsTitle"] = "Monitored persons",
            ["monUsers.personsSubtitle"] = "Device links and assigned monitors",
            ["monUsers.searchPh"] = "Search monitored people or monitors...",
            ["monUsers.all"] = "All",
            ["monUsers.noFilter"] = "No monitored persons for current filters.",
            ["monUsers.thPerson"] = "Person",
            ["monUsers.thDevice"] = "Device",
            ["monUsers.thMonitoredBy"] = "Monitored by",
            ["monUsers.thStatus"] = "Status",
            ["monUsers.thLastUpdate"] = "Last Update",
            ["monUsers.thActions"] = "Actions",
            ["monUsers.details"] = "Details",

            // Simulation page
            ["sim.title"] = "Simulations",
            ["sim.subtitle"] = "Send simulated data to monitored devices",
            ["sim.tools"] = "Tools",
            ["sim.loading"] = "Loading users and devices...",
            ["sim.retry"] = "Retry",
            ["sim.devicesTitle"] = "Monitored devices",
            ["sim.devicesReady"] = "devices ready for simulation",
            ["sim.generateAll"] = "Generate all",
            ["sim.startAutoAll"] = "Start auto all",
            ["sim.stopAutoAll"] = "Stop auto all",
            ["sim.refresh"] = "Refresh",
            ["sim.searchPh"] = "Search by name, serial, user...",
            ["sim.all"] = "All",
            ["sim.running"] = "Running",
            ["sim.idle"] = "Idle",
            ["sim.noPersons"] = "No monitored persons found.",
            ["sim.noMatch"] = "No devices match your search or filter.",
            ["sim.serial"] = "Serial:",
            ["sim.user"] = "User:",
            ["sim.sending"] = "Sending...",
            ["sim.generateOnce"] = "Generate once",
            ["sim.autoRunning"] = "Auto running",
            ["sim.startAuto"] = "Start auto",
            ["sim.stop"] = "Stop",

            // View Selected User
            ["viewUser.loading"] = "Loading user...",
            ["viewUser.notFound"] = "User not found.",
            ["viewUser.back"] = "← Back to Users",
            ["viewUser.emailConfirmed"] = "Email confirmed",
            ["viewUser.emailNotConfirmed"] = "Email not confirmed",
            ["viewUser.monitoredPeople"] = "Monitored People",
            ["viewUser.noMonitored"] = "No monitored people.",
            ["viewUser.details"] = "Details",
        };

        // ── Română ──
        private static readonly Dictionary<string, string> _ro = new()
        {
            // Header / Nav
            ["nav.dashboard"] = "Panou",
            ["nav.monitored"] = "Monitorizați",
            ["nav.notifications"] = "Notificări",
            ["nav.profile"] = "Profilul meu",
            ["nav.settings"] = "Setări",
            ["nav.aboutUs"] = "Despre noi",
            ["nav.support"] = "Suport",
            ["nav.logout"] = "Deconectare",
            ["nav.menu"] = "Meniu",

            // Login
            ["login.title"] = "LifeAlert +",
            ["login.tagline"] = "Pentru că fiecare bătaie a inimii contează",
            ["login.email"] = "Email",
            ["login.password"] = "Parolă",
            ["login.button"] = "Autentificare",
            ["login.loading"] = "Se autentifică...",
            ["login.or"] = "sau",
            ["login.google"] = "Autentificare cu Google",
            ["login.forgotPassword"] = "Ai uitat parola?",
            ["login.createAccount"] = "Creează un cont nou",
            ["login.resetPassword"] = "Resetare parolă",
            ["login.resetText"] = "Introduceți adresa de email și vă vom trimite un link pentru resetarea parolei.",
            ["login.sendResetLink"] = "Trimite link de resetare",
            ["login.cancel"] = "Anulare",
            ["login.close"] = "Închide",

            // Login errors
            ["login.error.failed"] = "Autentificare eșuată.",
            ["login.error.generic"] = "A apărut o eroare la autentificare.",
            ["login.error.enterEmail"] = "Te rugăm să introduci adresa de email.",
            ["login.error.validEmail"] = "Te rugăm să introduci o adresă de email validă.",
            ["login.error.resetFailed"] = "Trimiterea emailului de resetare a eșuat. Te rugăm să încerci din nou.",
            ["login.error.resetGeneric"] = "A apărut o eroare. Te rugăm să încerci mai târziu.",

            // Register
            ["register.title"] = "Înregistrare",
            ["register.loading"] = "Se înregistrează...",
            ["register.firstName"] = "Prenume",
            ["register.lastName"] = "Nume",
            ["register.email"] = "Email",
            ["register.password"] = "Parolă",
            ["register.confirmPassword"] = "Confirmare parolă",
            ["register.hasAccount"] = "Ai deja un cont? Autentifică-te",
            ["register.success"] = "Înregistrare reușită",
            ["register.emailSent"] = "Un email a fost trimis pentru verificare.",
            ["register.ok"] = "OK",

            // Register errors
            ["register.error.allRequired"] = "Toate câmpurile sunt obligatorii.",
            ["register.error.passwordMismatch"] = "Parolele nu coincid.",
            ["register.error.failed"] = "Înregistrarea a eșuat. Te rugăm să încerci din nou.",

            // Password validation
            ["password.required"] = "Parola este obligatorie.",
            ["password.minLength"] = "Parola trebuie să aibă cel puțin 8 caractere.",
            ["password.lowercase"] = "Parola trebuie să conțină cel puțin o literă mică.",
            ["password.uppercase"] = "Parola trebuie să conțină cel puțin o literă mare.",
            ["password.number"] = "Parola trebuie să conțină cel puțin o cifră.",
            ["password.special"] = "Parola trebuie să conțină cel puțin un caracter special.",

            // Dashboard
            ["dashboard.title"] = "Panou de control",
            ["dashboard.welcome"] = "Bine ai revenit, {0}! Iată o privire de ansamblu asupra monitorizării sănătății.",
            ["dashboard.totalMonitored"] = "Total monitorizați",
            ["dashboard.activeAlerts"] = "Alerte active",
            ["dashboard.stableStatus"] = "Status stabil",
            ["dashboard.usersOffline"] = "Utilizatori offline",
            ["dashboard.measurementsToday"] = "Măsurători totale azi",
            ["dashboard.monitoredPeople"] = "Persoane monitorizate",
            ["dashboard.viewAll"] = "Vezi toate →",

            // Shared card labels
            ["card.pulse"] = "Puls (bpm)",
            ["card.spo2"] = "SpO₂ (%)",
            ["card.temperature"] = "Temperatură (°C)",
            ["card.gps"] = "📍 GPS:",
            ["card.fallDetection"] = "🧭 Detectare cădere:",
            ["card.lastUpdate"] = "⏰ Ultima actualizare:",
            ["card.location"] = "Locație",
            ["card.call"] = "Apel",
            ["card.text"] = "Mesaj",
            ["card.na"] = "N/A",

            // Status
            ["status.ok"] = "OK",
            ["status.warning"] = "Atenție",
            ["status.critical"] = "Critic",
            ["status.offline"] = "Offline",
            ["status.online"] = "Online",

            // Monitored page
            ["monitored.title"] = "Persoane monitorizate",
            ["monitored.subtitle"] = "Gestionează și vizualizează toate persoanele monitorizate",
            ["monitored.addPerson"] = "Adaugă persoană",
            ["monitored.statusFilter"] = "Filtru status:",
            ["monitored.connectionFilter"] = "Filtru conexiune:",
            ["monitored.all"] = "Toate",
            ["monitored.alert"] = "Alertă",
            ["monitored.checkNeeded"] = "Verificare necesară",
            ["monitored.stable"] = "Stabil",
            ["monitored.online"] = "Online",
            ["monitored.offline"] = "Offline",
            ["monitored.loading"] = "Se încarcă persoanele monitorizate...",
            ["monitored.noMonitored"] = "Nicio persoană monitorizată",
            ["monitored.addToStart"] = "Adaugă o persoană pentru a primi date ESP.",
            ["monitored.noResults"] = "Niciun rezultat găsit",
            ["monitored.noMatch"] = "Nicio persoană monitorizată nu corespunde filtrelor selectate.",
            ["monitored.ageYears"] = "ani",
            ["monitored.ageNA"] = "Vârstă N/A",

            // Add person modal
            ["modal.addPerson"] = "Adaugă persoană monitorizată",
            ["modal.firstName"] = "Prenume",
            ["modal.lastName"] = "Nume",
            ["modal.birthdate"] = "Data nașterii",
            ["modal.gender"] = "Gen",
            ["modal.select"] = "Selectează...",
            ["modal.male"] = "Masculin",
            ["modal.female"] = "Feminin",
            ["modal.other"] = "Altul",
            ["modal.address"] = "Adresă",
            ["modal.deviceSerial"] = "Număr serial dispozitiv",
            ["modal.relationship"] = "Relație",
            ["modal.cancel"] = "Anulare",
            ["modal.addButton"] = "Adaugă persoană",

            // Settings
            ["settings.title"] = "⚙️ Setări",
            ["settings.subtitle"] = "Personalizează aplicația conform preferințelor tale",
            ["settings.appearance"] = "🎨 Aspect",
            ["settings.firstDay"] = "Prima zi a săptămânii",
            ["settings.fontSize"] = "Dimensiune font",
            ["settings.fontSizeDesc"] = "Ajustează dimensiunea textului în aplicație",
            ["settings.small"] = "Mic",
            ["settings.medium"] = "Mediu",
            ["settings.large"] = "Mare",
            ["settings.monday"] = "Luni",
            ["settings.tuesday"] = "Marți",
            ["settings.wednesday"] = "Miercuri",
            ["settings.thursday"] = "Joi",
            ["settings.friday"] = "Vineri",
            ["settings.saturday"] = "Sâmbătă",
            ["settings.sunday"] = "Duminică",
            ["settings.alertThresholds"] = "🚨 Praguri de alertă",
            ["settings.heartRate"] = "❤️ Ritm cardiac",
            ["settings.heartRateMin"] = "Ritm cardiac minim",
            ["settings.heartRateMax"] = "Ritm cardiac maxim",
            ["settings.temperatureSection"] = "🌡️ Temperatură",
            ["settings.tempMin"] = "Temperatură minimă",
            ["settings.tempMax"] = "Temperatură maximă",
            ["settings.resetDefaults"] = "🔄 Resetare la valorile implicite",
            ["settings.dataManagement"] = "💾 Gestionare date",
            ["settings.updateFrequency"] = "Frecvența actualizării datelor",
            ["settings.updateFrequencyDesc"] = "Cât de des se actualizează datele semnelor vitale (în secunde)",
            ["settings.every10s"] = "La fiecare 10 secunde",
            ["settings.every15s"] = "La fiecare 15 secunde",
            ["settings.every30s"] = "La fiecare 30 secunde",
            ["settings.every1m"] = "La fiecare 1 minut",
            ["settings.every2m"] = "La fiecare 2 minute",
            ["settings.every5m"] = "La fiecare 5 minute",
            ["settings.historyRetention"] = "Durata păstrării istoricului",
            ["settings.historyRetentionDesc"] = "Cât timp se păstrează datele vechi",
            ["settings.30days"] = "30 zile",
            ["settings.90days"] = "90 zile",
            ["settings.6months"] = "6 luni",
            ["settings.1year"] = "1 an",
            ["settings.unlimited"] = "Nelimitat",
            ["settings.system"] = "🔧 Sistem",
            ["settings.language"] = "Limbă",
            ["settings.languageDesc"] = "Selectează limba aplicației",
            ["settings.systemInfo"] = "📊 Informații sistem",
            ["settings.appVersion"] = "Versiune aplicație:",
            ["settings.lastUpdate"] = "Ultima actualizare:",
            ["settings.usedSpace"] = "Spațiu utilizat:",
            ["settings.saveAll"] = "💾 Salvează toate setările",
            ["settings.resetAll"] = "🔄 Resetare completă",
            ["settings.saved"] = "✅ Setările au fost salvate cu succes!",

            // Notifications
            ["notifications.title"] = "Notificări",
            ["notifications.subtitle"] = "Fii la curent cu toate alertele și actualizările de sănătate",
            ["notifications.criticalAlerts"] = "Alerte critice",
            ["notifications.warnings"] = "Avertismente",
            ["notifications.infoMessages"] = "Mesaje informative",
            ["notifications.unread"] = "Necitite",

            // Support
            ["support.tagline"] = "Suntem aici să te ajutăm",
            ["support.title"] = "Suport",
            ["support.backToDashboard"] = "← Înapoi la panou",

            // Profile
            ["profile.memberSince"] = "Membru din {0}",
            ["profile.personalInfo"] = "📋 Informații personale",
            ["profile.edit"] = "✏️ Editare",
            ["profile.save"] = "💾 Salvare",
            ["profile.cancel"] = "✖️ Anulare",
            ["profile.firstName"] = "Prenume",
            ["profile.lastName"] = "Nume",
            ["profile.security"] = "🔒 Securitate",
            ["profile.changePassword"] = "Schimbare parolă",

            // Common
            ["common.save"] = "Salvare",
            ["common.cancel"] = "Anulare",
            ["common.close"] = "Închide",
            ["common.loading"] = "Se încarcă...",
            ["common.retry"] = "Reîncercare",
            ["common.details"] = "Detalii",
            ["common.bpm"] = "bpm",
            ["common.celsius"] = "°C",

            // About Us
            ["about.title"] = "Despre LifeAlertPlus",
            ["about.intro"] = "LifeAlertPlus este un sistem de monitorizare bazat pe IoT, conceput pentru a îmbunătăți siguranța și calitatea vieții persoanelor vârstnice. Prin combinarea technologiei purtabile cu o platformă web modernă, sistemul permite monitorizarea în timp real a activității și a datelor legate de sănătate.",
            ["about.missionTitle"] = "Misiunea noastră",
            ["about.missionText"] = "Misiunea noastră este să sprijinim viața independentă, asigurând în același timp siguranța prin monitorizare continuă și alerte în timp util. LifeAlertPlus ajută îngrijitorii și membrii familiei să fie informați și să reacționeze rapid în caz de situații neobișnuite.",
            ["about.problemTitle"] = "Problema",
            ["about.problemText"] = "Multe persoane vârstnice trăiesc singure sau petrec perioade lungi fără supraveghere directă. Incidentele precum căderile, inactivitatea sau problemele subite de sănătate pot trece neobservate, ducând la asistență întârziată și riscuri crescute.",
            ["about.visionTitle"] = "Viziunea noastră",
            ["about.visionText"] = "Ne propunem să creăm un sistem de monitorizare fiabil și accesibil care sporește siguranța, promovează independența și oferă liniște sufletească atât utilizatorilor, cât și familiilor lor.",
            ["about.solutionTitle"] = "Soluția noastră",
            ["about.solutionIntro"] = "LifeAlertPlus oferă o soluție completă care integrează:",
            ["about.solutionWearable"] = "Dispozitiv IoT purtabil pentru colectarea datelor de activitate",
            ["about.solutionWeb"] = "Aplicație web pentru monitorizare în timp real",
            ["about.solutionAlerts"] = "Mecanisme de alertă pentru detectarea situațiilor anormale",
            ["about.featuresTitle"] = "Funcționalități cheie",
            ["about.feature1"] = "Monitorizare în timp real a activității",
            ["about.feature2"] = "Autentificare securizată și gestionare utilizatori",
            ["about.feature3"] = "Notificări și alerte prin email",
            ["about.feature4"] = "Panou de control pentru îngrijitori și administratori",
            ["about.feature5"] = "Arhitectură extensibilă pentru îmbunătățiri viitoare",
            ["about.disclaimerTitle"] = "Declinare responsabilitate",
            ["about.disclaimerText"] = "LifeAlertPlus nu este un dispozitiv medical și nu înlocuiește serviciile medicale profesionale sau sistemele de urgență. În caz de urgență, vă rugăm să contactați imediat serviciile locale de urgență.",

            // Support (extended)
            ["support.intro"] = "Suntem aici pentru a vă ajuta să vă asigurați că sistemul LifeAlertPlus funcționează fiabil și eficient.",
            ["support.contactTitle"] = "Contactați-ne",
            ["support.contactText"] = "Dacă întâmpinați probleme cu aplicația sau dispozitivul IoT, vă rugăm să contactați echipa noastră de suport:",
            ["support.contactNote"] = "Ne propunem să răspundem tuturor solicitărilor cât mai curând posibil.",
            ["support.beforeTitle"] = "Înainte de a contacta suportul",
            ["support.beforeText"] = "Pentru a rezolva rapid problemele frecvente, vă rugăm să verificați următoarele:",
            ["support.checkCharged"] = "Asigurați-vă că dispozitivul este încărcat corespunzător",
            ["support.checkRestart"] = "Reporniți dispozitivul",
            ["support.checkInternet"] = "Verificați că dispozitivul are o conexiune activă la internet",
            ["support.checkUpdate"] = "Asigurați-vă că aplicația este actualizată",
            ["support.commonTitle"] = "Probleme frecvente",
            ["support.issueNoData"] = "Dispozitivul nu trimite date",
            ["support.issueBattery"] = "Verificați nivelul bateriei",
            ["support.issueRestart"] = "Reporniți dispozitivul",
            ["support.issueNotLoading"] = "Aplicația nu încarcă date",
            ["support.issueRefresh"] = "Reîmprospătați pagina",
            ["support.issueConnection"] = "Verificați conexiunea la internet",
            ["support.issueLogin"] = "Probleme de autentificare",
            ["support.issueResetPw"] = "Resetați parola",
            ["support.issueVerifyEmail"] = "Asigurați-vă că emailul este verificat",
            ["support.techTitle"] = "Suport tehnic",
            ["support.techText"] = "Pentru întrebări tehnice sau probleme legate de sistem, vă rugăm să includeți:",
            ["support.techDesc"] = "O descriere a problemei",
            ["support.techSteps"] = "Pași pentru reproducerea problemei",
            ["support.techScreenshots"] = "Capturi de ecran (dacă sunt disponibile)",
            ["support.autoTitle"] = "Emailuri automate",
            ["support.autoText"] = "Mesajele generate de sistem (verificare cont, resetare parolă, notificări) sunt trimise de la:",
            ["support.autoNote"] = "Această adresă nu este monitorizată pentru mesaje primite.",
            ["support.noticeTitle"] = "Aviz de serviciu",
            ["support.noticeText"] = "LifeAlertPlus este conceput pentru a asista monitorizarea și alertarea, dar nu garantează prevenirea incidentelor. Bazați-vă întotdeauna pe serviciile de urgență în situații critice.",

            // Profile (extended)
            ["profile.changePicture"] = "Schimbă poza",
            ["profile.monitored"] = "Monitorizați",
            ["profile.activeAlerts"] = "Alerte active",
            ["profile.lastChanged"] = "Ultima modificare:",
            ["profile.never"] = "Niciodată",
            ["profile.changePasswordBtn"] = "Schimbă parola",
            ["profile.changeEmailTitle"] = "Schimbă emailul",
            ["profile.updateEmailDesc"] = "Actualizează adresa ta de email",
            ["profile.changeEmailBtn"] = "Schimbă emailul",
            ["profile.passwordManaged"] = "Parolă gestionată extern",
            ["profile.passwordManagedText"] = "Parola ta este gestionată prin",
            ["profile.emailManaged"] = "Email gestionat extern",
            ["profile.emailManagedText"] = "Emailul tău este gestionat prin",
            ["profile.notifPrefs"] = "Preferințe notificări",
            ["profile.emailNotif"] = "Notificări prin email",
            ["profile.emailNotifDesc"] = "Primește alerte importante prin email",
            ["profile.pushNotif"] = "Notificări push",
            ["profile.pushNotifDesc"] = "Alerte în timp real în browser",
            ["profile.criticalAlerts"] = "Alerte critice",
            ["profile.criticalAlertsDesc"] = "Notificări prioritare pentru situații de urgență",
            ["profile.dailySummary"] = "Rezumat zilnic",
            ["profile.dailySummaryDesc"] = "Primește un raport zilnic de activitate",
            ["profile.dangerZone"] = "Zonă periculoasă",
            ["profile.deleteAccount"] = "Șterge contul",
            ["profile.deleteAccountDesc"] = "Acțiune permanentă, toate datele vor fi șterse",
            ["profile.deletePermanently"] = "Șterge permanent",
            ["profile.currentPassword"] = "Parola curentă",
            ["profile.currentPasswordPh"] = "Introduceți parola curentă",
            ["profile.newPassword"] = "Parolă nouă",
            ["profile.newPasswordPh"] = "Cel puțin 8 caractere",
            ["profile.confirmNewPassword"] = "Confirmă parola nouă",
            ["profile.confirmNewPasswordPh"] = "Reintroduceți parola nouă",
            ["profile.newEmail"] = "Email nou",
            ["profile.newEmailPh"] = "Introduceți noua adresă de email",
            ["profile.confirmNewEmail"] = "Confirmă emailul nou",
            ["profile.confirmNewEmailPh"] = "Reintroduceți noua adresă de email",
            ["profile.passwordToConfirmPh"] = "Introduceți parola pentru confirmare",
            ["profile.emailChangedSuccess"] = "Email schimbat cu succes",
            ["profile.emailChangedText1"] = "Cererea de schimbare a adresei de email a fost trimisă cu succes!",
            ["profile.emailChangedText2"] = "Un email de confirmare a fost trimis la noua ta adresă de email. Verifică inbox-ul și apasă pe linkul de verificare pentru a finaliza procesul.",
            ["profile.emailChangedText3"] = "Din motive de securitate, am trimis și o notificare la adresa ta actuală de email. Dacă nu tu ai făcut această solicitare, poți anula din acel email.",
            ["profile.emailChangedNote"] = "Din motive de securitate, vei fi deconectat automat. Te rugăm să te autentifici din nou cu noua adresă de email după verificare.",
            ["profile.okLogout"] = "OK, Deconectează-mă",
            ["profile.passwordChangedSuccess"] = "Parolă schimbată cu succes",
            ["profile.passwordChangedText1"] = "Parola ta a fost schimbată cu succes!",
            ["profile.passwordChangedText2"] = "Te rugăm să folosești noua parolă la următoarea autentificare.",
            ["profile.ok"] = "OK",
            ["profile.areYouSure"] = "Ești sigur?",
            ["profile.deleteConfirm1"] = "Ești sigur că vrei să ștergi contul permanent?",
            ["profile.deleteConfirm2"] = "Această acțiune nu poate fi anulată.",
            ["profile.deleteConfirm3"] = "Asigură-te că ai salvat toate datele importante înainte de a continua.",
            ["profile.deleteConfirm4"] = "Toate datele tale vor fi eliminate permanent din sistemul nostru.",
            ["profile.yes"] = "Da",
            ["profile.accountDeleted"] = "Cont șters",
            ["profile.accountDeletedText"] = "Contul tău a fost șters permanent. Îți mulțumim că ai folosit serviciul nostru.",

            // Reset Password
            ["reset.password"] = "Parolă",
            ["reset.confirmPassword"] = "Confirmare parolă",
            ["reset.button"] = "Resetare parolă",
            ["reset.backToLogin"] = "Înapoi la autentificare",

            // Reset password errors
            ["reset.error.invalidLink"] = "Link de resetare invalid. Te rugăm să soliciți o nouă resetare a parolei.",
            ["reset.error.passwordMismatch"] = "Parolele nu coincid.",
            ["reset.error.success"] = "Parola a fost resetată cu succes! Redirecționare către autentificare...",
            ["reset.error.expired"] = "Linkul de resetare a expirat. Te rugăm să soliciți o nouă resetare a parolei.",
            ["reset.error.failed"] = "Resetarea parolei a eșuat. Te rugăm să încerci din nou.",
            ["reset.error.generic"] = "A apărut o eroare. Te rugăm să încerci mai târziu.",

            // Selected Monitored
            ["selected.goBack"] = "Înapoi la lista de monitorizați",
            ["selected.export"] = "Exportă",
            ["selected.years"] = "ani",
            ["selected.noAgeGender"] = "Fără informații vârstă/gen",
            ["selected.lastUpdate"] = "Ultima actualizare:",
            ["selected.device"] = "Dispozitiv:",
            ["selected.editProfile"] = "Editare profil",
            ["selected.heartRate"] = "Ritm cardiac",
            ["selected.noRecentMeasurements"] = "Fără măsurători recente.",
            ["selected.noData"] = "Date indisponibile",
            ["selected.bloodOxygen"] = "Oxigen în sânge (SpO₂)",
            ["selected.temperature"] = "Temperatură",
            ["selected.gpsLocation"] = "Locație GPS",
            ["selected.vitalSigns"] = "Evoluția semnelor vitale",
            ["selected.daily"] = "Zilnic",
            ["selected.weekly"] = "Săptămânal",
            ["selected.recentAlerts"] = "Alerte recente",
            ["selected.recentMeasurements"] = "Măsurători recente",
            ["selected.loading"] = "Se încarcă...",
            ["selected.notFound"] = "Persoana monitorizată nu a fost găsită.",
            ["selected.firstName"] = "Prenume",
            ["selected.lastName"] = "Nume",
            ["selected.gender"] = "Gen",
            ["selected.select"] = "Selectează...",
            ["selected.male"] = "Masculin",
            ["selected.female"] = "Feminin",
            ["selected.other"] = "Altul",
            ["selected.birthdate"] = "Data nașterii",
            ["selected.address"] = "Adresă",
            ["selected.deviceSerial"] = "Număr serial dispozitiv",
            ["selected.customRanges"] = "Intervale vitale personalizate (lasă gol pentru valorile implicite ale contului)",
            ["selected.minHr"] = "Ritm cardiac minim (bpm)",
            ["selected.maxHr"] = "Ritm cardiac maxim (bpm)",
            ["selected.minTemp"] = "Temperatură minimă (°C)",
            ["selected.maxTemp"] = "Temperatură maximă (°C)",
            ["selected.updateFrequency"] = "Frecvența actualizării (lasă gol pentru valoarea implicită: {0} s)",
            ["selected.useDefault"] = "Folosește valoarea implicită ({0} s)",
            ["selected.saving"] = "Se salvează...",

            // Relationships
            ["rel.select"] = "Selectează...",
            ["rel.mother"] = "Mamă",
            ["rel.father"] = "Tată",
            ["rel.grandmother"] = "Bunică",
            ["rel.grandfather"] = "Bunic",
            ["rel.aunt"] = "Mătușă",
            ["rel.uncle"] = "Unchi",
            ["rel.husband"] = "Soț",
            ["rel.wife"] = "Soție",
            ["rel.sister"] = "Soră",
            ["rel.brother"] = "Frate",
            ["rel.friend"] = "Prieten",
            ["rel.daughter"] = "Fiică",
            ["rel.son"] = "Fiu",
            ["rel.nephew"] = "Nepot",
            ["rel.niece"] = "Nepoată",

            // App
            ["app.notFound"] = "Pagină negăsită",
            ["app.notFoundText"] = "Ne pare rău, nu există nimic la această adresă.",

            // Admin
            ["admin.title"] = "Centru administrare",
            ["admin.subtitle"] = "Afișează toți utilizatorii și persoanele monitorizate",
            ["admin.liveData"] = "Date live",
            ["admin.loadingData"] = "Se încarcă datele...",
            ["admin.noData"] = "Nu s-au găsit utilizatori sau persoane monitorizate.",
            ["admin.totalUsers"] = "Total utilizatori",
            ["admin.monitoredPersons"] = "Persoane monitorizate",
            ["admin.online"] = "Online",
            ["admin.offline"] = "Offline",
            ["admin.alerts"] = "Alerte",
            ["admin.todayMeasurements"] = "Măsurători azi",
            ["admin.notifications"] = "Notificări",
            ["admin.noNotifications"] = "Fără notificări",

            // Admin Nav
            ["adminNav.dashboard"] = "Panou",
            ["adminNav.monitoreds"] = "Monitorizați",
            ["adminNav.users"] = "Utilizatori",
            ["adminNav.simulations"] = "Simulări",
            ["adminNav.logout"] = "Deconectare",
            ["adminNav.menu"] = "Meniu",
            ["adminNav.profile"] = "Profilul meu",
            ["adminNav.settings"] = "Setări",

            // Users page
            ["users.title"] = "Centru utilizatori",
            ["users.subtitle"] = "Prezentare conturi și status",
            ["users.liveOverview"] = "Prezentare live",
            ["users.totalUsers"] = "Total utilizatori",
            ["users.activeUsers"] = "Utilizatori activi",
            ["users.inactiveUsers"] = "Utilizatori inactivi",
            ["users.emailConfirmed"] = "Email confirmat",
            ["users.loading"] = "Se încarcă utilizatorii...",
            ["users.retry"] = "Reîncercare",
            ["users.usersTitle"] = "Utilizatori",
            ["users.searchPh"] = "Caută utilizatori...",
            ["users.all"] = "Toți",
            ["users.active"] = "Activi",
            ["users.inactive"] = "Inactivi",
            ["users.noUsersFound"] = "Nu s-au găsit utilizatori pentru filtrul curent.",
            ["users.thUser"] = "Utilizator",
            ["users.thEmail"] = "Email",
            ["users.thMonitored"] = "Monitorizați",
            ["users.thProvider"] = "Furnizor",
            ["users.thStatus"] = "Status",
            ["users.thEmailConfirmed"] = "Email confirmat",
            ["users.thActions"] = "Acțiuni",
            ["users.details"] = "Detalii",
            ["users.deactivate"] = "Dezactivare",
            ["users.activate"] = "Activare",
            ["users.delete"] = "Ștergere",

            // Monitored Users page
            ["monUsers.title"] = "Centru monitorizați",
            ["monUsers.subtitle"] = "Persoane monitorizate și monitorii lor",
            ["monUsers.liveOverview"] = "Prezentare live",
            ["monUsers.monitored"] = "Monitorizați",
            ["monUsers.online"] = "Online",
            ["monUsers.offline"] = "Offline",
            ["monUsers.alerts"] = "Alerte",
            ["monUsers.loading"] = "Se încarcă persoanele monitorizate...",
            ["monUsers.retry"] = "Reîncercare",
            ["monUsers.noPersons"] = "Nu s-au găsit persoane monitorizate.",
            ["monUsers.personsTitle"] = "Persoane monitorizate",
            ["monUsers.personsSubtitle"] = "Linkuri dispozitive și monitori asignați",
            ["monUsers.searchPh"] = "Caută persoane monitorizate sau monitori...",
            ["monUsers.all"] = "Toți",
            ["monUsers.noFilter"] = "Nicio persoană monitorizată pentru filtrele curente.",
            ["monUsers.thPerson"] = "Persoană",
            ["monUsers.thDevice"] = "Dispozitiv",
            ["monUsers.thMonitoredBy"] = "Monitorizat de",
            ["monUsers.thStatus"] = "Status",
            ["monUsers.thLastUpdate"] = "Ultima actualizare",
            ["monUsers.thActions"] = "Acțiuni",
            ["monUsers.details"] = "Detalii",

            // Simulation page
            ["sim.title"] = "Simulări",
            ["sim.subtitle"] = "Trimite date simulate către dispozitivele monitorizate",
            ["sim.tools"] = "Instrumente",
            ["sim.loading"] = "Se încarcă utilizatorii și dispozitivele...",
            ["sim.retry"] = "Reîncercare",
            ["sim.devicesTitle"] = "Dispozitive monitorizate",
            ["sim.devicesReady"] = "dispozitive pregătite pentru simulare",
            ["sim.generateAll"] = "Generează toate",
            ["sim.startAutoAll"] = "Pornește auto toate",
            ["sim.stopAutoAll"] = "Oprește auto toate",
            ["sim.refresh"] = "Reîmprospătare",
            ["sim.searchPh"] = "Caută după nume, serial, utilizator...",
            ["sim.all"] = "Toate",
            ["sim.running"] = "Rulează",
            ["sim.idle"] = "Inactiv",
            ["sim.noPersons"] = "Nu s-au găsit persoane monitorizate.",
            ["sim.noMatch"] = "Niciun dispozitiv nu corespunde căutării sau filtrului.",
            ["sim.serial"] = "Serial:",
            ["sim.user"] = "Utilizator:",
            ["sim.sending"] = "Se trimite...",
            ["sim.generateOnce"] = "Generează o dată",
            ["sim.autoRunning"] = "Auto rulează",
            ["sim.startAuto"] = "Pornește auto",
            ["sim.stop"] = "Oprește",

            // View Selected User
            ["viewUser.loading"] = "Se încarcă utilizatorul...",
            ["viewUser.notFound"] = "Utilizator negăsit.",
            ["viewUser.back"] = "← Înapoi la utilizatori",
            ["viewUser.emailConfirmed"] = "Email confirmat",
            ["viewUser.emailNotConfirmed"] = "Email neconfirmat",
            ["viewUser.monitoredPeople"] = "Persoane monitorizate",
            ["viewUser.noMonitored"] = "Nicio persoană monitorizată.",
            ["viewUser.details"] = "Detalii",
        };
    }
}
